export const PRESCRIPTION_STATUS = {
  DRAFT: "draft",
  CREATED: "created",
  PDF_GENERATED: "pdf_generated",
  SENT: "sent",
  RECEIVED: "received",
  VALIDATED_BY_PATIENT: "validated_by_patient",
  ACTIVE: "active",
  COMPLETED: "completed",
  CANCELLED: "cancelled",
  UPDATED: "updated",
};

const TRANSITIONS = {
  [PRESCRIPTION_STATUS.DRAFT]: [PRESCRIPTION_STATUS.CREATED, PRESCRIPTION_STATUS.CANCELLED],
  [PRESCRIPTION_STATUS.CREATED]: [
    PRESCRIPTION_STATUS.PDF_GENERATED,
    PRESCRIPTION_STATUS.UPDATED,
    PRESCRIPTION_STATUS.CANCELLED,
  ],
  [PRESCRIPTION_STATUS.PDF_GENERATED]: [
    PRESCRIPTION_STATUS.SENT,
    PRESCRIPTION_STATUS.UPDATED,
    PRESCRIPTION_STATUS.CANCELLED,
  ],
  [PRESCRIPTION_STATUS.SENT]: [
    PRESCRIPTION_STATUS.RECEIVED,
    PRESCRIPTION_STATUS.UPDATED,
    PRESCRIPTION_STATUS.CANCELLED,
  ],
  [PRESCRIPTION_STATUS.RECEIVED]: [
    PRESCRIPTION_STATUS.VALIDATED_BY_PATIENT,
    PRESCRIPTION_STATUS.CANCELLED,
  ],
  [PRESCRIPTION_STATUS.VALIDATED_BY_PATIENT]: [PRESCRIPTION_STATUS.ACTIVE],
  [PRESCRIPTION_STATUS.ACTIVE]: [PRESCRIPTION_STATUS.COMPLETED, PRESCRIPTION_STATUS.CANCELLED],
  [PRESCRIPTION_STATUS.COMPLETED]: [],
  [PRESCRIPTION_STATUS.CANCELLED]: [],
  [PRESCRIPTION_STATUS.UPDATED]: [
    PRESCRIPTION_STATUS.PDF_GENERATED,
    PRESCRIPTION_STATUS.SENT,
    PRESCRIPTION_STATUS.CANCELLED,
  ],
};

export const isValidPrescriptionStatus = (status) =>
  Object.values(PRESCRIPTION_STATUS).includes(status);

export const canTransitionPrescriptionStatus = (fromStatus, toStatus) => {
  if (!isValidPrescriptionStatus(toStatus)) return false;
  if (!fromStatus) return true;
  if (!isValidPrescriptionStatus(fromStatus)) return false;

  const allowed = TRANSITIONS[fromStatus] || [];
  return allowed.includes(toStatus);
};

export const RECEIVED_OR_ACTIONABLE_STATUSES = [
  PRESCRIPTION_STATUS.SENT,
  PRESCRIPTION_STATUS.RECEIVED,
  PRESCRIPTION_STATUS.VALIDATED_BY_PATIENT,
  PRESCRIPTION_STATUS.ACTIVE,
];
